travis:
  secure:
    BINSTAR_TOKEN: 2PArJHQMVRpx9k9gK5+q8PkyZ8v14ONRYuBMtsuOzQVnnQRLy6HZ8kAgKPqcXHjEFGBYbUMRWWPrxmxdRk1GGYP2T4cy+1GFOOzYyQ+vaNb02J+nnyqLiaUQPJhYGR6hSlKIS9M0InNJF3B/nkLpJr6aheTahcU0YFjFYMzidUDQ2M/bu81xU1b8LTwuxlpPNHqDK/tUW4M5m+NeI/7NdyuPC5pS0YN9suXZNMA8B2n27+Tjii5TA28wHFHKTeOwjdLogOoUvet3a94fv4HSF6j6r8mlyXL2guiiKi7aZipcE1BavDuZIjXrkrrwprEr4zskqj/MFhxwWQDumJSDvA6QtDng39EVH+M4dzNShnG448bgRW/9Pg2ha3NwMxB01uuiPGG8PUgH4nQuEG4BJ9drP4Jmjrh/XooF2Agztc+6v9Lxdprs6i5Gx7krqmvSaBVfid+x/ghhNLcx8aqSLDWKGADzBk6EsUYO36DJDyP4+GvVavYKyDhkMQPkj+asnxSmyx+RWRk4wHpAfd33ncAIzfRypnI2TdChPJjZ7S2s6GyR7/VJr84jULIQ5G/mm5RxwNn45ZYP+U5Rd4TK2SzWBCz8JlsfeEwUni1yJ81yG+46zZbNAZ2NBlb+++ce+i7oXyGCmpR/Y3+fAQkjmaNo19S4wEIns+LvTufsyuo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
