travis:
  secure:
    BINSTAR_TOKEN: rrXcX5x5DiANu2TECDk8EfKslw8FXH6HTc8TenAOIvQH/ftMpBa6A85oi6hszRMxdVYQbiyiMIi2lllMW9aF09GWQ1poLqeIfGeiaSUrPLrVtRm8S6bUT+4uXt/kOfOVTlxQUiCUGe4IhwOIKzR9oiZZWYBjGwc4qOLNidwDXBw0fqOtoG5AG20kPjUur01ksQUKqX5/wlyVVcw0Zma+aUcfWawZHIzFFiy4u634W0qeIN5LywPN8KVE2id+Ri/EsNbJQEtMxxJDmUtUOH/sJLTK2d3mWGuFiyx8lpVrvVwoNkPWyc8bkRFyzNEvvF4gLhaymLpkm0b+ZLU1t85F7SCILfS2T0toVAwJJT/aewZRsdaITVGbLUsZnSM/NtldzXNf2dNXpWZjBdNC0OIgybOAhO2zaEox88JaWlUv77EcLFeYTENK3OAQ9rfxE7KcC9fndE+8iJPCiZPo5QIW6Lct/PbXZn89RPkASgRuIm2gVXHnL4qP9CqouTE5bSkVfn7nfwvFCuGv6H3AYxoBfP1Z88HcwtI1gnUU4eBzg8DJk0NAYuYf7swlK7OstUaMq52TzYhnIHwNgoVa+MdiR2FvpyqJeAvh8DhXUNJkDCGqs70qyagBdFc3EPlwR8A/RHZU0jwGzVJgG/fK9/33AZ3XFgldpiYUSRI6Dswebhg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
